### ISSUE TITLE
カンファレンスページを勢い良くめくってると死ぬ

### ISSUE THREAD

**Issue by sys1yagi** [mhidaka/EventApp#17]
onSaveStateなんとか辺りがあやしい。

```
03-20 20:22:56.511: E/AndroidRuntime(9969): java.lang.NullPointerException
03-20 20:22:56.511: E/AndroidRuntime(9969):     at org.techbooster.app.abc.tools.GsonParcer.unwrap(GsonParcer.java:46)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at org.techbooster.app.abc.fragments.ConferenceSessionFragment.onActivityCreated(ConferenceSessionFragment.java:61)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1508)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.view.ViewPager.smoothScrollTo(ViewPager.java:800)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:565)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:551)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v4.view.ViewPager.onTouchEvent(ViewPager.java:2015)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.View.dispatchTouchEvent(View.java:7706)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.dispatchTouchEvent(ActionBarActivityDelegateICS.java:260)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.View.dispatchPointerEvent(View.java:7886)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
03-20 20:22:56.511: E/AndroidRuntime(9969):     at android.
```

**Comment by realeyez77** [comment]
こんなんも出ました

```
03-20 20:33:44.457: E/AndroidRuntime(23489): java.lang.NullPointerException
03-20 20:33:44.457: E/AndroidRuntime(23489):    at org.techbooster.app.abc.loaders.ConferenceSessionLoader$1.onResponse(ConferenceSessionLoader.java:51)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at org.techbooster.app.abc.tools.VolleyManager$1.onResponse(VolleyManager.java:41)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at org.techbooster.app.abc.tools.VolleyManager$1.onResponse(VolleyManager.java:38)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at android.os.Handler.handleCallback(Handler.java:725)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at android.os.Handler.dispatchMessage(Handler.java:92)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at android.os.Looper.loop(Looper.java:213)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at android.app.ActivityThread.main(ActivityThread.java:5092)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at java.lang.reflect.Method.invokeNative(Native Method)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at java.lang.reflect.Method.invoke(Method.java:511)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
03-20 20:33:44.457: E/AndroidRuntime(23489):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sys1yagi** [comment]
ありがとうございますー
そのエラーは恐らく #12 で直っています。
次のリリースに含めますー
